- hosts: kub-1-master
  become: yes
  tasks:
    - name: create token
      shell: kubeadm token create
      register: create_token
    - name: get hash
      shell: openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | \ openssl dgst -sha256 -hex | sed 's/^.* //'
      register: get_hash
- hosts: nodes
  become: yes
  tasks:
    - name: join cluster
      shell:
        cmd: kubeadm join --token {{hostvars['kub-1-master']['create_token'].stdout}} 192.168.8.30:6443 --discovery-token-ca-cert-hash sha256:{{hostvars['kub-1-master']['get_hash'].stdout}}
